### ISSUE TITLE
For loops being weird

### ISSUE THREAD

**Issue by matthewd673** [neon2d/neon2d#35]
I'm working on a little game with neon but whenever I hit the for-loop it freezes. Any ideas for how I could get this to work (its in `update()`).

```
for (int i = 0; i <= monsterct; i++) //monsterct is amount of monsters
            {
                if (monslist[i] != null) //monslist is array of the monster class (contains physics.rect)
                {
                    gameScene.render(new Prop(enemy, (int)monslist[monsterct].col.x, (int)monslist[monsterct].col.y, 32, 32));
                }
            }
```

**Comment by DontBelieveMe** [comment]
Could you put the code in a branch or something - it might be specific to your code.
My tests with for loops are running fine.

**Comment by matthewd673** [comment]
Sure thing

**Comment by matthewd673** [comment]
Okay, the project is up and on branch [for-loop-project](https://github.com/neon2d/neon2d/tree/for-loop-project)

**Comment by DontBelieveMe** [comment]
Your issue is that you are using `monsterct`as the index in `gameScene.render(...)` and not `i`.
The reason it is crashing is becuase the amount of monsters should always be one more than the index of the monster - arrays are zero indexed/based, amounts are not.
So if you change 
`new Prop(enemy, (int)monslist[monsterct].col.x, (int)monslist[monsterct].col.y, 32, 32))`
to 
`new Prop(enemy, (int)monslist[i].col.x, (int)monslist[i].col.y, 32, 32))`
It should work.

**Comment by matthewd673** [comment]
Thanks, didn't even notice I had done that
